services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports: 
      - 4567:5432
    env_file:
      - .env.test
  node_app:
    container_name: node_app
    build: ./back-end
    image: node_app_image
    ports:
      - 5000:5000
    command: ["npm","run", "test"]
    depends_on: 
      - postgres_db
    env_file:
      - .env.test