name: Deploy on Aws EC2
on:
  push:
    branches:
      - main
      - master
jobs:
  Deploy-My-Software:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Health
        run: echo "Starting"
      - name: Checkout Repository Code
        uses: actions/checkout@v3
      - name: List Files
        run: ls ${{ github.workspace }}
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          directory: back-end/
          file_name: .env
          fail_on_empty: true
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          directory: front-end/
          file_name: .env
          fail_on_empty: true
      - name: Build process
        run: docker-compose build
      - name: Run docker compose
        run: docker-compose down && docker-compose up -d
