name: Testing file on Pull Request
on: [pull_request]
jobs:
  Test-File:
    runs-on: ubuntu-latest
    steps:
      - name: Health
        run: echo "Estou iniciando"
      - name: Checkout Repository Code
        uses: actions/checkout@v3
      - name: List Files
        run: ls ${{ github.workspace }}
