name: Testing file on Pull Request
on: [pull_request]

jobs:
  Test-File:
    runs-on: ubuntu-latest
    steps:
      - name: Health
        run: echo "Estou iniciando"
      - name: Checkout Repository Code
        uses: actions/checkout@v3
      - name: List Files
        run: ls ${{ github.workspace }}
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "banco"
          envkey_DATABASE_URL: "postgres://postgres:postgres@postgres_db:5432/banco"
          file_name: .env.test
      - name: Run Tests
        run: docker-compose -f docker-compose-test.yml up
        run: docker-compose down
